# -*- coding: utf-8 -*-
"""Log analysis in colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TH8l1QuzglWHhZ5E6d0baWLVefdint-k
"""

#-------------------------------------------------------------
#This is just normal code to read how many lines in the log file

f = open('sample.log','r')
count = 0
i = f.readline()
while i:
    count = count + 1
    i = f.readline()
print(count)

f.close()

"""Count Requests from the given file

    - Parse the provided log file to extract all IP addresses.
    - Calculate the number of requests made by each IP address.
    - Sort and display the results in descending order of request counts.
"""

#This library is to returns a list containing all matches
#or search the string type in this give line of text
import re

f = open('sample.log','r')
x = []
log_entry = f.readline()
while log_entry :
    # To find all IP addresses in the log data
    y = re.findall(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b', log_entry)
    x.append(y)
    log_entry = f.readline()

ip_set = {}
for a in range(len(x)):
  ip_set[x[a][0]] = 0
for a in range(len(x)):
  ip_set[x[a][0]] += 1
print("Total for each IP Address")
print("IP Address","\t","Request Count")
for i in ip_set:
  print(i,"\t",ip_set[i])

import re
f = open('sample.log','r')
log_entry = f.readline()

list_endpoints = []
while log_entry:
  #e = re.findall(r'\b\d{1,9}\b ', a)
  match = re.findall(r'"[A-Z]+ (\S+) HTTP', log_entry)
  list_endpoints.append(match[0])
  log_entry = f.readline()

endpoints_dict = {}
for i in list_endpoints:
  endpoints_dict[i] = 0
for i in list_endpoints:
  endpoints_dict[i] += 1


max_count = 0
for i in endpoints_dict:
  if endpoints_dict[i] > max_count :
    (endpoint,max_count) = (i,endpoints_dict[i])
print("Most acessed endpoints is \t : ")
print("Endpoint",endpoint,"Accessed",max_count,"times")

import re
f = open('sample.log','r')
log_entry = f.readline()

ip_add = {}
while log_entry:
  e = re.findall(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b ', log_entry)
  x = re.search("Invalid credentials", log_entry)
  ip_add[e[0]] = 0
  log_entry = f.readline()
f.close()

#-----------------------------------------------------------------------
# NOTE --> DON'T RUN THIS CELL DIRECTLY OR DON'T RUN IT ALONE-----------
# BEFORE RUNNING THIS CELL YOU HAVE TO RUN PREVIOUS CELL----------------
#ELSE --> THE OUTPUT IS INCREMENTAL-------------------------------------
#-----------------------------------------------------------------------
import re
f = open('sample.log','r')
log_entry = f.readline()
while log_entry:
  e = re.findall(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b ', log_entry)
  if re.search("Invalid credentials", log_entry):
    ip_add[e[0]] = ip_add[e[0]]+1
  else :
    pass
  log_entry = f.readline()

print("Suspicious Activity Detected:")
print("IP Address","\t","Failed Login Attempts")
for i in ip_add :
  if ip_add[i] != 0 :
    print(i,"\t",ip_add[i])
f.close()


#Dont run this multiple times