# -*- coding: utf-8 -*-
"""VRV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TH8l1QuzglWHhZ5E6d0baWLVefdint-k
"""

f = open('sample.log','r')
count = 0
i = f.readline()
while i:
    count = count + 1
    i = f.readline()
print(count)

f.close()

#This library is to returns a list containing all matches
#or search the string type in this give line of text
import re

f = open('sample.log','r')
x = []
log_entry = f.readline()
while log_entry :
    # To find all IP addresses in the log data
    y = re.findall(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b', log_entry)
    x.append(y)
    log_entry = f.readline()

ip_set = {}
for a in range(len(x)):
  ip_set[x[a][0]] = 0
for a in range(len(x)):
  ip_set[x[a][0]] += 1
print("Total for each IP Address")
print("IP Address","\t","Request Count")
for i in ip_set:
  print(i,"\t",ip_set[i])

import re
f = open('sample.log','r')
log_entry = f.readline()

l = {}
while log_entry:
  e = re.findall(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b ', log_entry)
  x = re.search("Invalid credentials", log_entry)
  l[e[0]] = 0
  log_entry = f.readline()
f.close()

#-----------------------------------------------------------------------
# NOTE --> DON'T RUN THIS CELL DIRECTLY OR DON'T RUN IT ALONE-----------
# BEFORE RUNNING THIS CELL YOU HAVE TO RUN PREVIOUS CELL----------------
#ELSE --> THE OUTPUT IS INCREMENTAL-------------------------------------
#-----------------------------------------------------------------------
import re
f = open('sample.log','r')
log_entry = f.readline()
while log_entry:
  e = re.findall(r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b ', log_entry)
  if re.search("Invalid credentials", log_entry):
    l[e[0]] = l[e[0]]+1
  else :
    pass
  log_entry = f.readline()

print("Suspicious Activity Detected:")
print("IP Address","\t","Failed Login Attempts")
for i in l :
  if l[i] != 0 :
    print(i,"\t",l[i])
f.close()

import re
f = open('sample.log','r')
log_entry = f.readline()

l = []
while log_entry:
  #e = re.findall(r'\b\d{1,9}\b ', a)
  match = re.findall(r'"[A-Z]+ (\S+) HTTP', log_entry)
  l.append(match[0])
  log_entry = f.readline()

m = {}
for i in l:
  m[i] = 0
for i in l:
  m[i] += 1


max_count = 0
for i in m:
  if m[i] > max_count :
    (endpoint,max_count) = (i,m[i])
print("Most acessed endpoints is \t : ")
print("Endpoint",endpoint,"Accessed",max_count,"times")